apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: facedetect
  labels:
    app: backend
    service: backend
spec:
  ports:
  - name: http-backend
    port: 5001
    targetPort: http
    protocol: TCP
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: facedetect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      imagePullSecrets:
        - name: gitlab-auth
      containers:
        - name:  backend
          # Insert the path to the image on the registry 
          #  e.g. registry.gitlab.com/username/images/backend:latest
          image: "" 
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
