{
 "title": "Demonstration",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cluster 1 - avg CPU usage of nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=\"johan-cluster-1-k8s-master-nf-1\", container!~\"\"}[2m]))",
     "legendFormat": "Master node"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=\"johan-cluster-1-k8s-node-nf-1\", container!~\"\"}[2m]))",
     "legendFormat": "node 1"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=\"johan-cluster-1-k8s-node-nf-2\", container!~\"\"}[2m]))",
     "legendFormat": "node 2"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=\"johan-cluster-1-k8s-node-nf-3\", container!~\"\"}[2m]))",
     "legendFormat": "node 3"
    }
   ]
  },
  {
   "title": "Cluster 2 - avg CPU usage of nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=\"johan-cluster-2-k8s-master-nf-1\", container!~\"\"}[2m]))",
     "legendFormat": "Master node"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=\"johan-cluster-2-k8s-node-nf-1\", container!~\"\"}[2m]))",
     "legendFormat": "node 1"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=\"johan-cluster-2-k8s-node-nf-2\", container!~\"\"}[2m]))",
     "legendFormat": "node 2"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=\"johan-cluster-2-k8s-node-nf-3\", container!~\"\"}[2m]))",
     "legendFormat": "node 3"
    }
   ]
  },
  {
   "title": "Cluster 3 - avg CPU usage of nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=\"johan-cluster-3-k8s-master-nf-1\", container!~\"\"}[2m]))",
     "legendFormat": "Master node"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=\"johan-cluster-3-k8s-node-nf-1\", container!~\"\"}[2m]))",
     "legendFormat": "node 1"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=\"johan-cluster-3-k8s-node-nf-2\", container!~\"\"}[2m]))",
     "legendFormat": "node 2"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=\"johan-cluster-3-k8s-node-nf-3\", container!~\"\"}[2m]))",
     "legendFormat": "node 3"
    }
   ]
  },
  {
   "title": "Cluster 1 - avg CPU usage of application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "avg CPU usage" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"facedetect\", container=\"frontend\"}[2m]))",
     "legendFormat": "Frontend"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"facedetect\", container=\"backend\"}[2m]))",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Cluster 2 - avg CPU usage of application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "avg CPU usage" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"facedetect\", container=\"frontend\"}[2m]))",
     "legendFormat": "Frontend"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"facedetect\", container=\"backend-v2\"}[2m]))",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Cluster 3 - avg CPU usage of application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "avg CPU usage" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"facedetect\", container=\"frontend\"}[2m]))",
     "legendFormat": "Frontend"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"facedetect\", container=\"backend-v2\"}[2m]))",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Cluster 1 - traffic to application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"facedetect\", pod=~\"frontend.*\"}[2m]))",
     "legendFormat": "Frontend"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"facedetect\", pod=~\"backend-v2.*\"}[2m]))",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Cluster 2 - traffic to application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"facedetect\", pod=~\"frontend.*\"}[2m]))",
     "legendFormat": "Frontend"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"facedetect\", pod=~\"backend-v2.*\"}[2m]))",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Cluster 3 - traffic to application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"facedetect\", pod=~\"frontend.*\"}[2m]))",
     "legendFormat": "Frontend"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"facedetect\", pod=~\"backend-v2.*\"}[2m]))",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Cluster 1 - read/writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=\"facedetect\", container=\"frontend\"}[2m])) + sum(irate(container_fs_reads_total{namespace=\"facedetect\", container=\"frontend\"}[2m]))",
     "legendFormat": "Frontend"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=\"facedetect\", container=\"backend-v1\"}[2m])) + sum(irate(container_fs_reads_total{namespace=\"facedetect\", container=\"backend-v1\"}[2m]))",
     "legendFormat": "Backend v1"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=\"facedetect\", container=\"backend-v2\"}[2m])) + sum(irate(container_fs_reads_total{namespace=\"facedetect\", container=\"backend-v2\"}[2m]))",
     "legendFormat": "Backend v2"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=\"facedetect\", container=\"storage\"}[2m])) + sum(irate(container_fs_reads_total{namespace=\"facedetect\", container=\"storage\"}[2m]))",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "Cluster 2 - read/writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=\"facedetect\", container=\"frontend\"}[2m])) + sum(irate(container_fs_reads_total{namespace=\"facedetect\", container=\"frontend\"}[2m]))",
     "legendFormat": "Frontend"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=\"facedetect\", container=\"backend-v1\"}[2m])) + sum(irate(container_fs_reads_total{namespace=\"facedetect\", container=\"backend-v1\"}[2m]))",
     "legendFormat": "Backend v1"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=\"facedetect\", container=\"backend-v2\"}[2m])) + sum(irate(container_fs_reads_total{namespace=\"facedetect\", container=\"backend-v2\"}[2m]))",
     "legendFormat": "Backend v2"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=\"facedetect\", container=\"storage\"}[2m])) + sum(irate(container_fs_reads_total{namespace=\"facedetect\", container=\"storage\"}[2m]))",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "Cluster 2 - read/writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=\"facedetect\", container=\"frontend\"}[2m])) + sum(irate(container_fs_reads_total{namespace=\"facedetect\", container=\"frontend\"}[2m]))",
     "legendFormat": "Frontend"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=\"facedetect\", container=\"backend-v1\"}[2m])) + sum(irate(container_fs_reads_total{namespace=\"facedetect\", container=\"backend-v1\"}[2m]))",
     "legendFormat": "Backend v1"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=\"facedetect\", container=\"backend-v2\"}[2m])) + sum(irate(container_fs_reads_total{namespace=\"facedetect\", container=\"backend-v2\"}[2m]))",
     "legendFormat": "Backend v2"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=\"facedetect\", container=\"storage\"}[2m])) + sum(irate(container_fs_reads_total{namespace=\"facedetect\", container=\"storage\"}[2m]))",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "Istio system avg CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace='istio-system', container!=\"POD\"}[2m]))",
     "legendFormat": "Cluster 1"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace='istio-system', container!=\"POD\"}[2m]))",
     "legendFormat": "Cluster 2"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace='istio-system', container!=\"POD\"}[2m]))",
     "legendFormat": "Cluster 3"
    }
   ]
  },
  {
   "title": "Istio system avg network usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"istio-system\"}[2m]))",
     "legendFormat": "Cluster 1"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"istio-system\"}[2m]))",
     "legendFormat": "Cluster 2"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"istio-system\"}[2m]))",
     "legendFormat": "Cluster 3"
    }
   ]
  }
 ]
}